[profile.default]
gas_reports = ["*"]
gas_reports_ignore = []
ignored_error_codes = []
optimizer = true
optimizer_runs = 999999
solc_version = "6"
verbosity = 3
block_number = 20_270_778
block_timestamp = 1_726_598_340
fork_block_number = 20_772_164
rpc_storage_caching = { chains = ["mainnet"], endpoints = "all" }
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./gas-profiles"}]

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
